# Generated by Django 5.2.17 on 2026-08-13 09:12

from django.db import migrations


def backfill_profiles(apps, schema_editor):
    """Create a Profile for every existing user that lacks one."""
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
